services:
  db:
    image: mariadb:10
    container_name: gestao_saude_db
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: "]5Y7iiGxjF35"
      MARIADB_DATABASE: gestao_saude_db
      MARIADB_USER: gestao_saude_user
      MARIADB_PASSWORD: "3v8iX7si6U4x"
    volumes:
      - mariadb_data:/var/lib/mysql
    ports:
      - "3306:3306"

  app:
    build: .
    container_name: gestao_saude_app
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      DATABASE_URL: "mysql+pymysql://gestao_saude_user:3v8iX7si6U4x@db:3306/gestao_saude_db"

  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: always
    ports:
      - "9000:9000"
      - "8000:8000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

volumes:
  mariadb_data:
  portainer_data:
