[default]
SECRET_KEY="endLines-switchs-SMS-2023"
EXTENSIONS=[
  "app.ext.database",
  "app.ext.auth",
  "app.blueprints.views",
]

SQLALCHEMY_DATABASE_URI = "mysql+pymysql://root:kain4348@135.148.62.245:9001/conecta_mais"