apiVersion: apps/v1
kind: Deployment
metadata:
  name: gestao-saude-app
  labels:
    app: gestao-saude-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gestao-saude-app
  template:
    metadata:
      labels:
        app: gestao-saude-app
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 10001
        runAsGroup: 10001
      containers:
        - name: app
          image: gestao-saude-app:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 5000
          envFrom:
            - configMapRef:
                name: gestao-saude-config
            - secretRef:
                name: gestao-saude-secret
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 20
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
