apiVersion: apps/v1
kind: Deployment
metadata:
  name: gestao-saude-db
  labels:
    app: gestao-saude-db
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: gestao-saude-db
  template:
    metadata:
      labels:
        app: gestao-saude-db
    spec:
      containers:
        - name: db
          image: mariadb:10
          imagePullPolicy: IfNotPresent
          ports:
            - name: mysql
              containerPort: 3306
          envFrom:
            - configMapRef:
                name: gestao-saude-config
            - secretRef:
                name: gestao-saude-secret
          volumeMounts:
            - name: mariadb-data
              mountPath: /var/lib/mysql
          readinessProbe:
            exec:
              command: ["healthcheck.sh", "--connect", "--innodb_initialized"]
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          livenessProbe:
            exec:
              command: ["healthcheck.sh", "--connect", "--innodb_initialized"]
            initialDelaySeconds: 30
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 3
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 1000m
              memory: 1Gi
      volumes:
        - name: mariadb-data
          persistentVolumeClaim:
            claimName: gestao-saude-db-pvc
