apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gestao-saude-db-pvc
  labels:
    app: gestao-saude-db
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
