apiVersion: v1
kind: Secret
metadata:
  name: gestao-saude-secret
  labels:
    app: gestao-saude
type: Opaque
stringData:
  DATABASE_URL: "mysql+pymysql://gestao_saude_user:CHANGE_ME@db:3306/gestao_saude_db"
  SECRET_KEY: "CHANGE_ME"
  EMAIL_USER: "noreply@example.com"
  EMAIL_PASSWORD: "CHANGE_ME"
  MARIADB_ROOT_PASSWORD: "CHANGE_ME"
  MARIADB_PASSWORD: "CHANGE_ME"
