apiVersion: v1
kind: Service
metadata:
  name: db
  labels:
    app: gestao-saude-db
spec:
  type: ClusterIP
  selector:
    app: gestao-saude-db
  ports:
    - name: mysql
      port: 3306
      targetPort: mysql
