name: CM COMPOSE

on:
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Debug login
        run: |
          echo "Actor: ${{ github.actor }}"
          echo "Repo: ${{ github.repository }}"
          docker info
          
      - name: Build Docker image
        run: |
          docker build -t ghcr.io/edmaker89/conecta_mais:latest -f Dockerfile .
          docker tag ghcr.io/edmaker89/conecta_mais:latest ghcr.io/edmaker89/conecta_mais:${{ github.sha }}

      - name: Push Docker image
        run: |
          docker push ghcr.io/edmaker89/conecta_mais:latest
          docker push ghcr.io/edmaker89/conecta_mais:${{ github.sha }}
