name: CM COMPOSE

on:
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - uses: azure/docker-login@v1
      with:
        login-server: ghcr.io
        username: ${{ secrets.GH_PACKAGES_USER }}
        password: ${{ secrets.GH_PACKAGES_TOKEN }}

    - run: |
        docker build -t ghcr.io/edmaker/conecta_mais:latest -f Dockerfile .
        docker tag ghcr.io/edmaker/conecta_mais:latest ghcr.io/edmaker/conecta_mais:${{ github.sha }}

    - run: |
        docker push ghcr.io/edmaker/conecta_mais:latest
        docker push ghcr.io/edmaker/conecta_mais:${{ github.sha }}
