name: CM COMPOSE

on:
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t ghcr.io/edmaker/conecta_mais/cm-compose:latest -f Dockerfile .
          docker tag ghcr.io/edmaker/conecta_mais/cm-compose:latest ghcr.io/edmaker/conecta_mais/cm-compose:${{ github.sha }}

      - name: Push Docker image
        run: |
          docker push ghcr.io/edmaker/conecta_mais/cm-compose:latest
          docker push ghcr.io/edmaker/conecta_mais/cm-compose:${{ github.sha }}
